"""
AI Marker and Cliché Detection Database
Identifies hallmark lexical patterns, transition phrases, and stylistic structures
disproportionately generated by Large Language Models (ChatGPT, Claude, Gemini, LLaMA).
"""

import re
from typing import List, Dict, Any, Tuple

# Single words that LLMs heavily over-index on compared to human writing
AI_BUZZWORDS = {
    "delve": "Over-utilized LLM verb rarely found in natural student/human academic prose.",
    "delving": "Characteristic AI exploratory transition participle.",
    "tapestry": "Stereotypical LLM metaphor for complexity or integration.",
    "testament": "Formulaic phrase component ('stands as a testament to').",
    "beacon": "High-frequency LLM metaphor for hope, guidance, or excellence.",
    "multifaceted": "Generic LLM academic adjective used to simulate depth.",
    "paramount": "Overused formal adjective favoured by generative models.",
    "pivotal": "Overused signpost word in LLM analytical essays.",
    "underscores": "Favoured LLM analytical verb instead of 'shows' or 'indicates'.",
    "fosters": "Stereotypical LLM verb for social/positive impact.",
    "intertwined": "Favoured relational adjective in generative writing.",
    "interconnected": "Frequent LLM structural adjective.",
    "seamless": "Standard LLM marketing/descriptive superlative.",
    "seamlessly": "High-frequency AI adverb.",
    "landscape": "Overused LLM metaphor for domain, context, or industry.",
    "realm": "Frequent AI abstraction word.",
    "nuanced": "Heavily over-represented in synthetic analytical prose.",
    "harness": "Common AI action verb for utilizing tools or concepts.",
    "harnessing": "Frequent AI participle starter.",
    "crucial": "Disproportionate frequency in LLM instructional/argumentative text.",
    "vital": "High-frequency emphasis word in generative text.",
    "imperative": "Favoured LLM formal imperative.",
    "meticulous": "Typical synthetic praise or process adjective.",
    "meticulously": "Stereotypical LLM adverb.",
    "unwavering": "Formulaic synthetic descriptive modifier.",
    "embark": "Dramatic LLM journey metaphor.",
    "embarking": "Dramatic LLM transition participle.",
    "unravel": "High-frequency AI exploratory metaphor.",
    "unraveling": "AI analytical participle.",
    "dynamic": "Overused modifier in LLM descriptions.",
    "resonate": "Typical synthetic emotional/conceptual connection word.",
    "resonates": "Typical synthetic concept connector.",
    "holistic": "Generic LLM comprehensive adjective.",
    "quintessential": "Overused synthetic superlative.",
    "culmination": "Standard AI concluding noun.",
    "myriad": "High-frequency formal quantifier in AI essays.",
    "plethora": "Overused synthetic variety descriptor.",
    "intricate": "Stereotypical AI descriptor for systems or ideas.",
    "intricacies": "Overused LLM noun for details or complexities.",
    "cornerstone": "Standard AI structural metaphor.",
    "catalyst": "Frequent AI causal metaphor.",
    "furthermore": "Over-represented mechanical transition connector.",
    "moreover": "Over-represented formal additive connector.",
    "notably": "Favoured LLM attention marker.",
    "revolutionize": "Standard AI superlative verb for technological progress.",
    "transformative": "Generic LLM impact adjective."
}

# Multi-word transition formulas and boilerplate phrases
AI_PHRASES = [
    (r"\b(?:it is|it's) (?:important|essential|crucial|imperative|worth noting) to (?:remember|note|recognize|understand)\b", 
     "Formulaic LLM hedging and signposting pattern."),
    (r"\bstands as a testament to\b", 
     "Classic synthetic rhetorical flourish."),
    (r"\bplays a (?:pivotal|crucial|vital|significant) role in\b", 
     "Stereotypical LLM importance attribution."),
    (r"\bin (?:today's|the contemporary) (?:fast-paced|rapidly evolving|ever-changing) world\b", 
     "Generic boilerplate introductory cliché."),
    (r"\bdelve (?:deeper|into)\b", 
     "LLM-specific exploratory expression."),
    (r"\ba rich tapestry of\b", 
     "High-confidence generative AI metaphor."),
    (r"\bat its (?:very )?core\b", 
     "Common LLM conceptual reduction phrase."),
    (r"\bshed(?:s|ding)? light on\b", 
     "Favoured AI clarification idiom."),
    (r"\bnot only\b.*?\bbut also\b", 
     "Symmetrical balance construction frequently over-indexed by LLMs."),
    (r"\bin conclusion,?\b", 
     "Formulaic schoolbook closing transition."),
    (r"\bto sum up,?\b", 
     "Mechanical closing signpost."),
    (r"\ball in all,?\b", 
     "Mechanical transition."),
    (r"\bin summary,?\b", 
     "Mechanical summary signpost."),
    (r"\bon the other hand,?\b", 
     "Textbook contrast transition."),
    (r"\bnavigating the complexities of\b", 
     "Stereotypical AI problem-solving metaphor."),
    (r"\bpaving the way for\b", 
     "Standard generative progress idiom."),
    (r"\bshaping the future of\b", 
     "Standard synthetic forward-looking cliché."),
    (r"\ba wide array of\b", 
     "Generic AI diversity signpost."),
    (r"\bby understanding\b.*?\bwe can\b", 
     "Didactic pedagogical closure typical of instruction-tuned models."),
    (r"\bas we move forward,?\b", 
     "Generic AI narrative progression marker.")
]


def detect_cliches_in_sentence(sentence: str) -> Dict[str, Any]:
    """
    Scans an individual sentence for AI buzzwords and formulaic phrases.
    Returns matched items, flagged word count, and an AI marker density score.
    """
    sentence_clean = sentence.lower()
    matches = []
    
    # 1. Check multi-word phrase patterns
    for pattern, explanation in AI_PHRASES:
        for m in re.finditer(pattern, sentence_clean):
            matched_text = sentence[m.start():m.end()]
            matches.append({
                "type": "phrase",
                "term": matched_text,
                "start": m.start(),
                "end": m.end(),
                "explanation": explanation
            })
            
    # 2. Check individual buzzwords (word boundaries)
    words = re.findall(r"\b[a-zA-Z]+\b", sentence_clean)
    word_count = len(words)
    if word_count == 0:
        return {"matches": [], "score": 0.0, "buzzword_count": 0}

    buzzword_count = 0
    for word, explanation in AI_BUZZWORDS.items():
        # Match standalone word
        pattern = rf"\b{re.escape(word)}\b"
        for m in re.finditer(pattern, sentence_clean):
            # Check if this span is already part of a phrase match
            span_covered = any(pm["start"] <= m.start() and m.end() <= pm["end"] for pm in matches if pm["type"] == "phrase")
            if not span_covered:
                matched_text = sentence[m.start():m.end()]
                matches.append({
                    "type": "word",
                    "term": matched_text,
                    "start": m.start(),
                    "end": m.end(),
                    "explanation": explanation
                })
                buzzword_count += 1

    # Score calculation: 0.0 to 1.0 based on marker density
    phrase_weight = 0.35
    word_weight = 0.15
    raw_score = (len([m for m in matches if m["type"] == "phrase"]) * phrase_weight) + (buzzword_count * word_weight)
    
    # Normalize score against sentence length
    density_score = min(1.0, raw_score * (15.0 / max(10, word_count)))

    return {
        "matches": matches,
        "score": float(density_score),
        "buzzword_count": buzzword_count + len([m for m in matches if m["type"] == "phrase"])
    }


def analyze_document_cliches(sentences: List[str]) -> Dict[str, Any]:
    """
    Aggregates cliché statistics across the entire document.
    """
    total_matches = []
    total_buzzwords = 0
    total_score = 0.0
    
    for idx, sent in enumerate(sentences):
        res = detect_cliches_in_sentence(sent)
        if res["matches"]:
            for m in res["matches"]:
                m["sentence_index"] = idx
                total_matches.append(m)
        total_buzzwords += res["buzzword_count"]
        total_score += res["score"]
        
    num_sentences = max(1, len(sentences))
    avg_score = total_score / num_sentences
    
    return {
        "total_markers": len(total_matches),
        "total_buzzwords": total_buzzwords,
        "average_density_score": float(avg_score),
        "all_matches": total_matches
    }
