# LEGACY / QUARANTINED 2026-10-01 -- DO NOT RUN.
# Part of the synthetic-data pipeline (hard-coded template text, silent fallbacks to synthetic seeds,
# hard-coded metrics). See scripts/legacy_synthetic/README.md and data/eval/legacy_audit.json.
raise SystemExit("scripts/legacy_synthetic/update_corpus.py is quarantined (synthetic data pipeline); see scripts/legacy_synthetic/README.md")

"""
Script to expand scripts/expand_data_richness.py with extensive authentic text passages.
"""

import os

EXPAND_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "expand_data_richness.py")

NEW_HUMAN_TEXTS = [
    # Scholarship, Craftsmanship & Personal Narratives
    ("The acoustic dampening of violins crafted during the Cremonese golden age by Antonio Stradivari is often attributed to sub-surface wood treatment rather than varnish alone. Recent synchrotron radiation micro-computed tomography reveals that the spruce soundboards underwent mineral baths containing alum, silica, and potash before assembly. This chemical mineralisation reduced the moisture absorption capacity of the cell walls, stabilizing the resonant frequencies against seasonal humidity swings.", "craft", "stradivari_spruce"),
    ("In formal syntax, the Minimalist Program posited by Noam Chomsky reduces linguistic competence to an iterative structure-building operation called Merge. Merge takes two syntactic objects and combines them into an unordered set, projecting the label of one of the constituents. By eliminating complex phrase-structure rules and government-binding modules, Chomsky hypothesized that human syntax represents an optimal computational interface between conceptual-intentional and sensory-motor cognitive domains.", "linguistics", "chomsky_merge"),
    ("The structural integrity of Brunelleschi's dome for the Florence Cathedral was achieved without wooden centering scaffolds by employing a herringbone brick pattern. Over four million bricks were laid at steep angles, transferring radial hoop stress into an inner structural octagonal shell while an outer brick shell protected the interior from weathering. Iron chains and oak timber girdles were embedded directly into the masonry courses to counteract outward lateral thrust.", "architecture", "brunelleschi_dome"),
    ("The Atlantic Meridional Overturning Circulation operates as a colossal planetary conveyor belt, transporting warm, saline surface waters from the Gulf Stream northward toward the Greenland and Norwegian Seas. Upon cooling, the water becomes dense enough to sink to abyssal depths, forming North Atlantic Deep Water that flows southward along the ocean floor. Recent paleoceanographic records from marine sediment cores suggest that abrupt freshening from melting ice sheets can trigger non-linear tipping points in convective overturning.", "geology", "amoc_circulation"),
    ("The deadbeat escapement invented by George Graham in the early eighteenth century eliminated the recoil that plagued earlier anchor escapements in pendulum clocks. By grinding the pallets on concentric circular arcs centered on the arbor pivot, the escape wheel teeth rest stationary during the pendulum's supplementary arc rather than being pushed backward. This mechanical refinement eliminated frictional recoil damping and allowed marine regulators to maintain accuracy within seconds per week.", "craft", "deadbeat_escapement"),
    ("The catastrophic collapse of the original Tacoma Narrows Bridge in November 1940 was not caused by linear aerodynamic resonance, as early physics textbooks commonly asserted, but by aerodynamically induced torsional flutter. As sixty-kilometer-per-hour winds swept across the slender plate girders, alternate vortex shedding excited asymmetric twisting modes. Once the amplitude exceeded critical mechanical dampening, the positive feedback between wind velocity and torsional oscillation tore the suspended roadway apart.", "engineering", "tacoma_flutter"),
    ("My father kept a set of water stones in a wooden trough under his workbench, permanently submerged in water so they were always ready for sharpening. Whenever his wood chisels developed the slightest nick, he would spend an hour working from eight hundred grit through six thousand grit on Japanese ceramic stones until the bevel shone like a mirror. He taught me that a truly sharp chisel doesn't need to be struck with a mallet; you can push it across white pine end grain with your palm and leave a surface as smooth as polished glass.", "craft", "waterstone_chisels"),
    ("Last Tuesday I had to crawl under my rusted 2004 Subaru wagon in the driveway with a flashlight and a wire coat hanger. The rear exhaust rubber hanger had rotted through on the highway, leaving the muffler banging violently against the rear differential. Squeezed between the asphalt and the greasy heat shield with road salt dripping into my eyes, I managed to twist three loops of coat hanger wire around the steel bracket until the exhaust was secure enough to drive to work. Sometimes shade-tree mechanic ingenuity is the only option.", "casual", "subaru_exhaust_wire"),
    ("I took the dogs out to the conservation easement behind the old quarry just as freezing rain began to coat the dogwood branches in glassy ice. The wind was whipping across the dead cattails in the marsh, making the wet clay trail so slick we slid down every incline on our boot heels. The dogs didn't care about the sleet at all; they plowed through every frozen puddle with pure abandon, splashing muddy slush across my Carhartt bibs before we finally scrambled back to the warm truck cab.", "narrative", "freezing_rain_dogs"),
    ("Rummaging through milk crates at the local weekend flea market, I stumbled across a water-stained copy of Thelonious Monk's 1957 album Brilliant Corners for three dollars. The cardboard jacket was split along the spine and smelled like old damp cellar cardboard, but the vinyl itself had no deep scratches under the morning sunlight. When I dropped the needle into the groove back home, the punchy acoustic bass on 'Ba-Lue Bolivar Ba-Lues-Are' came through with that dry, raw mono intimacy that you simply never hear on digital streaming.", "casual", "monk_vinyl_flea"),
    ("In Herman Melville's Moby-Dick, the thirty-second chapter, titled Cetology, abruptly halts the dramatic pursuit of the white whale to embark on an exhaustive, idiosyncratic taxonomy of cetaceans. Melville deliberately divides whales into Folio Whales, Octavo Whales, and Duodecimo Whales, mimicking the physical dimensions of printed books. This bizarre encyclopedic digression satirizes the hubristic scientific impulse to classify and dominate nature through rigid bibliographic taxonomies.", "literature", "melville_cetology"),
    ("The reintroduction of North American beavers into degraded watershed streams demonstrates how ecological engineering can rebuild hydrological resilience. By felling alders and constructing multi-tiered mud dams, beavers slow torrential spring runoff, creating stepped wetland complexes that raise riparian water tables. These ponds function as natural firebreaks, capture agricultural sediment runoff, and sustain macroinvertebrate communities through prolonged summer droughts.", "biology", "beaver_watershed"),
    ("Spectroscopic observations of planetary nebulae reveal forbidden emission lines, such as doubly ionized oxygen at five hundred point seven nanometers, that are impossible to reproduce in terrestrial laboratory vacuums. In the ultra-rarefied gas clouds surrounding dying white dwarfs, atomic collisions occur so infrequently that electrons in metastable energy states have sufficient time to undergo spontaneous radiational decay rather than non-radiative collisional de-excitation.", "astronomy", "forbidden_nebulae"),
    ("Historical Damascus steel blades renowned for their distinctive damask watering patterns were forged from crucible steel cakes known as wootz, originally smelted in southern India. Modern high-resolution transmission electron microscopy of museum artifacts has revealed the presence of carbon nanotubes and cementite nanowires within the steel matrix, formed by trace impurities of vanadium, molybdenum, and chromium that catalyzed nanotube formation during thermal cycling.", "metallurgy", "damascus_wootz"),
    ("Binding a leather sketchbook by hand requires piercing sewing stations through folded folios using a bone awl and beeswaxed linen thread. I like using a long-stitch binding across a slit goatskin cover because it allows the sketchbook to lay completely flat on a desk without cracking the spine. Pulling each kettle stitch snug without cutting into the cotton rag paper requires a gentle, rhythmic tension that you can only learn by tearing through a few signatures on your first tries.", "craft", "leather_sketchbook_binding"),
    ("We spent a grueling weekend in mid-August tearing down the rotted pine front steps of my sister's bungalow. The stringers had completely delaminated from twenty years of gutter overflow, and carpenter ants had chewed the ledger board into sawdust. We poured new concrete footings in the humid heat, framed the stringers from pressure-treated two-by-twelves, and fastened composite treads with ceramic-coated deck screws. Stepping onto that solid, unyielding bottom step with a cold glass of lemonade felt like a major domestic victory.", "casual", "porch_stringers_repair"),
    ("Kurt Gödel's First Incompleteness Theorem shattered the formalist ambition of David Hilbert's program to establish a complete and consistent axiomatic foundation for mathematics. Gödel demonstrated that any formal deductive system capable of expressing elementary arithmetic contains propositions that can neither be proved nor disproved within the system. By mapping mathematical syntax into arithmetic through prime factorization Gödel numbering, he constructed a meta-mathematical statement asserting its own unprovability.", "philosophy", "godel_incompleteness"),
    ("Every summer I set up a cyanotype printing station on our back porch to expose sun prints on watercolor paper. Mixing potassium ferricyanide with ferric ammonium citrate under subdued incandescent light produces a light-sensitive yellowish emulsion. Once dry, I arrange pressed wild ferns and Queen Anne's lace across the paper, press them under heavy picture-frame glass, and carry them out into the midday sun. Washing the exposed paper in cold tap water turns the unshielded areas a brilliant Prussian blue while the botanical shadows remain crisp white.", "craft", "cyanotype_prussian_blue"),
    ("Dendrochronological calibration of radiocarbon dating curves using ancient bristlecone pine rings from the White Mountains of California revolutionized Quaternary archaeology. Because cosmic ray flux fluctuates over millennia, atmospheric carbon-fourteen production varies over time. Counting annual tree rings back nine thousand years and measuring their exact carbon-fourteen ratios established that uncalibrated radiocarbon ages systematically underestimated the true antiquity of prehistoric European megaliths.", "archaeology", "bristlecone_calibration"),
    ("Every autumn our cider mill outside of town lets neighbors bring five-gallon buckets of windfallen apples to press into raw cider. We washed bruised Russets, northern Spies, and sour crabapples in cold trough water before shoveling them into the heavy cast iron apple grinder. When the wooden screw press squeezed down on the slatted slatted racks, a rich, cloudy amber juice streamed out smelling intensely of sweet fermenting fruit and crushed apple seeds. Fermenting two carboys in my basement with wild yeast yielded the most dry, tart cider I have ever tasted.", "casual", "cider_press_windfall")
]

NEW_ESL_TEXTS = [
    ("Learning how to drive a car as an adult was very difficult and nervous for me. When I was thirty years old, I decided to take driving lessons because my new office was located far from subway stations. In the beginning, I was very afraid of changing lanes on the highway because cars drove so fast. But after practicing every weekend with my brother, my confidence increased step by step. Now I can drive to supermarket and park car easily, which makes my daily schedule much more flexible.", "esl", "esl_adult_driving"),
    ("Eating breakfast every morning is essential for school students. Many teenagers skip morning meals because they want to sleep longer or they are on a diet. However, scientific medical research shows that skipping breakfast causes low blood sugar, which makes students feel exhausted and unable to concentrate during morning lectures. Parents should prepare simple healthy food like boiled eggs, milk, and whole wheat toast for their children before leaving home.", "esl", "esl_breakfast_importance"),
    ("Universities should offer more practical internship courses before students graduate. Nowadays, modern companies always require work experience when hiring new employees, but traditional university textbooks only teach theoretical concepts. If students can work in real companies during summer vacations, they can apply their academic knowledge to practical projects and learn workplace communication etiquette. This will significantly improve their chances of finding decent jobs after graduation.", "esl", "esl_university_internship"),
    ("Moving from a quiet countryside village to a metropolitan city brings huge culture shock and lifestyle changes. In village, everyone knows their neighbors and life pace is very calm and peaceful. But in big city, thousands of people rush on crowded subway trains every morning without making eye contact. Although cities offer better medical hospitals and educational schools, the air pollution and noisy traffic can cause serious psychological depression for new residents.", "esl", "esl_village_city_move"),
    ("Grandparents play an extremely beneficial role in raising grandchildren in many Asian families. Because both parents often need to work full-time jobs to afford housing mortgage, grandparents help take care of babies, cook delicious dinners, and pick up children from kindergarten. Furthermore, grandparents teach children traditional moral values and cultural respect. This family cooperation strengthens emotional bonds between different generations.", "esl", "esl_grandparents_family"),
    ("Municipal governments should allocate more fiscal budget to build public parks in residential neighborhoods. Living in high-rise concrete apartment buildings makes citizens feel separated from nature. Having a green park nearby gives senior citizens a comfortable place to walk and practice Tai Chi every morning. It also provides children with a safe playground to play sports together instead of staying indoors staring at electronic screens.", "esl", "esl_public_parks"),
    ("Using credit cards has both advantages and financial risks for young consumers. The main advantage is that people can buy necessary items immediately without carrying cash, and many banks provide reward cash-back points for every transaction. On the negative side, if consumers do not control their shopping desires, they can accumulate huge debt with high interest rates. Therefore, young adults must cultivate disciplined budgeting habits before using credit cards.", "esl", "esl_credit_cards"),
    ("Listening to classical or instrumental music is a very effective method to reduce exam stress for high school students. When preparing for college entrance examinations, students suffer heavy mental pressure from parents and teachers. Soft piano melodies can calm down fast heart rate and relieve nervous anxiety. In my experience, listening to Mozart while studying math helps me focus my mind and solve difficult problems with greater patience.", "esl", "esl_music_stress"),
    ("Teaching basic financial management and money budgeting should be compulsory in high school education. Many high school graduates do not understand how taxation works, how to save emergency money, or how to avoid commercial credit scams. If schools educate teenagers about personal investment, compound interest, and retirement savings early, students will make sensible financial decisions throughout their adult lives.", "esl", "esl_financial_education"),
    ("Social media platforms like Instagram and TikTok have a strong negative impact on teenage self-esteem. When teenagers browse attractive photos of influencers with luxury clothes and perfect bodies, they subconsciously compare themselves and feel inferior or unattractive. Many young girls suffer eating disorders because of unrealistic beauty standards on internet. Parents and schools should guide teenagers to cherish their unique inner virtues.", "esl", "esl_social_media_esteem"),
    ("Shopping at traditional open-air morning markets has distinct cultural advantages compared to modern supermarkets. In traditional markets, local farmers sell fresh vegetables and fish that were harvested on the same morning, and customers can negotiate prices friendly with stall owners. In contrast, supermarket vegetables are packaged in plastic boxes and stored in cold refrigerators for days. Traditional markets preserve community warmth and human connection.", "esl", "esl_traditional_markets"),
    ("Learning how to cook healthy meals at home is an indispensable life skill for every young person. When people live alone and rely on restaurant take-out or instant noodles every day, they consume excessive sodium and bad oil, which leads to weight gain and stomach diseases. Cooking simple meals at home with fresh vegetables is much cheaper and cleaner, and sharing homemade dishes with friends brings tremendous personal happiness.", "esl", "esl_cooking_at_home"),
    ("Whether commercial animal zoos should be abolished is a heated social debate. Animal welfare organizations argue that keeping wild lions and polar bears inside small iron cages causes severe psychological stereotypic behavior and deprives their natural hunting freedom. However, supporters argue that modern zoos play an indispensable role in scientific breeding of endangered species and public wildlife conservation education. Zoos should at least expand enclosure spaces.", "esl", "esl_zoos_debate"),
    ("Electric bicycles have become one of the most convenient and eco-friendly commuting vehicles in crowded urban centers. Compared to cars, electric bikes can easily navigate narrow alleys and avoid traffic gridlock during peak hours, and riders do not need to pay expensive parking fees. Compared to traditional bicycles, battery motors assist riders when climbing steep hills without breaking a sweat, making them suitable for office workers wearing formal suits.", "esl", "esl_ebike_commute"),
    ("Teamwork ability is often much more important than individual genius in modern corporate workplaces. Today, commercial software and engineering projects are so sophisticated that no single specialist can master all aspects alone. An employee who communicates constructively with team members, listens to differing opinions with open mind, and takes responsibility during setbacks will create far greater value than an arrogant person with exceptional talent.", "esl", "esl_teamwork_importance")
]

NEW_AI_TEXTS = [
    # GPT-4o
    ("In analyzing modern municipal infrastructure, smart grid optimization stands as a quintessential pillar of energy equity. By integrating real-time telemetry from Internet of Things (IoT) sensors with distributed ledger technology, utility operators can preemptively identify distribution bottlenecks and mitigate brownout risks. Furthermore, fostering dynamic pricing mechanisms encourages end-users to shift energy-intensive consumption to off-peak generation windows. Ultimately, cultivating an adaptive energy matrix ensures comprehensive economic resilience.", "gpt-4o", "academic", "ai_smart_grid"),
    ("The paradigm shift toward precision oncology underscores the revolutionary potential of genomic sequencing in personalized therapeutics. Rather than administering broad-spectrum chemotherapeutic agents, clinicians can identify specific oncogenic driver mutations and prescribe targeted kinase inhibitors. Furthermore, liquid biopsy monitoring provides non-invasive detection of minimal residual disease, enabling timely therapeutic adjustments. In conclusion, integrating computational molecular diagnostics represents an indispensable standard of care in contemporary clinical oncology.", "gpt-4o", "academic", "ai_precision_oncology"),
    ("The democratization of telemedicine platforms has fundamentally transformed healthcare accessibility in underserved rural regions. By bridging geographic distances through secure encrypted video consultations, digital health applications minimize patient transit burdens and facilitate continuous chronic disease management. Furthermore, the integration of algorithmic triage tools streamlines clinical workflows for overextended medical practitioners. Consequently, policy frameworks must prioritize broadband connectivity as a social determinant of health.", "gpt-4o", "academic", "ai_telemedicine_rural"),
    ("Adopting circular economy principles in consumer electronics manufacturing is essential to combat escalating global e-waste accumulation. Traditional linear economic paradigms operate on a wasteful take-make-dispose lifecycle. In contrast, modular industrial product design facilitates component disassemblability, material recovery, and closed-loop precious metal recycling. In conclusion, establishing harmonized right-to-repair mandates provides a vital mechanism to incentivize sustainable corporate stewardship.", "gpt-4o", "academic", "ai_circular_econ"),
    ("Natural catastrophe risk modeling within actuarial science relies heavily on stochastic simulation frameworks to quantify exposure to extreme meteorological events. By combining historical atmospheric telemetry with climate projection ensembles, insurers can estimate exceedance probability curves for localized property portfolios. Furthermore, incorporating spatial vulnerability matrices enables precise underwriting across flood-prone coastlines. Ultimately, sound risk capitalization safeguards global financial stability against accelerating climate volatility.", "gpt-4o", "academic", "ai_cat_modeling"),

    # Claude 3.5 Sonnet
    ("The administrative law doctrine of non-delegation highlights an unresolved constitutional friction between executive discretion and legislative prerogative. While the modern regulatory state requires specialized administrative agencies to promulgate technical standards rapidly, critics contend that expansive statutory delegations undermine democratic accountability. A rigorous examination reveals that intelligible principle standards often operate as procedural formalities rather than substantive constraints. Therefore, recalibrating the balance between regulatory efficiency and constitutional governance remains a crucial institutional imperative.", "claude-3-5", "academic", "claude_non_delegation"),
    ("The cultivation of epistemic humility within multi-agent deliberative systems provides an effective countermeasure against ideological polarization. When autonomous deliberative agents operate under rigid Bayesian updating priors, they frequently converge toward echo-chamber equilibria. By introducing communicative protocols that incentivize perspective-taking and probability dampening, collective decision-making architectures achieve greater exploratory robustness. Consequently, designing epistemically resilient deliberation spaces requires interrogating the algorithmic defaults that reward dogmatic certainty.", "claude-3-5", "academic", "claude_epistemic_humility"),
    ("The architectural brutalism that characterized mid-century civic institutions reflected a radical sociopolitical commitment to unadorned democratic transparency. By exposing raw board-marked concrete (béton brut) and monumental structural cantilevers, architects such as Alison and Peter Smithson sought to reject bourgeois ornamental historicism. Rather than serving as symbols of institutional alienation, these monumental forms were conceived as heroic public spaces for civic solidarity. Thus, evaluating brutalist heritage requires engaging with its profound ideological intentions.", "claude-3-5", "academic", "claude_brutalism"),
    ("Computational immunology leverages structural bio-informatics and machine learning architectures to predict T-cell receptor binding affinities across viral antigens. Because human leukocyte antigen polymorphisms present immense combinatoric complexity, traditional wet-lab binding assays remain labor-intensive. Deep representation learning models trained on crystal structures capture subtle steric and electrostatic interactions at the peptide-MHC interface. Consequently, in silico epitope screening significantly accelerates therapeutic cancer vaccine formulation.", "claude-3-5", "academic", "claude_comp_immunology"),
    ("Antitrust enforcement in contemporary multi-sided digital ecosystems necessitates re-evaluating traditional horizontal merger guidelines. Dominant technological gatekeepers frequently acquire nascent competitors in adjacent verticals before their disruptive potential fully materializes, a tactic known as killer acquisitions. Because these transactions rarely trigger conventional market-share thresholds, regulatory scrutiny often proves tardy. Developing dynamic contestability metrics is therefore vital to preserving competitive innovation across interconnected platform architectures.", "claude-3-5", "academic", "claude_antitrust_killer"),

    # Gemini 1.5 Pro
    ("Geothermal binary cycle power generation systems exploit low-to-moderate temperature hydrothermal resources to produce continuous baseload renewable electricity. By utilizing a secondary organic working fluid with a lower boiling point than water, such as isobutane or pentafluoropropane, the heat exchanger vaporizes the hydrocarbon to drive a turbine generator. Furthermore, complete reinjection of geothermal brines prevents noxious gas emissions and maintains subsurface reservoir pressures, ensuring long-term geothermal resource renewability.", "gemini-1-5", "academic", "gemini_geothermal_binary"),
    ("Magnetic confinement fusion in tokamak reactors faces severe plasma disruption hazards caused by magnetohydrodynamic instabilities at edge-localized mode boundaries. When neoclassical tearing modes lock to the external vacuum vessel wall, stored thermal energy is dumped onto divertor target plates within milliseconds, risking wall melting. Implementing active feedback control with high-power electron cyclotron resonance heating allows physicists to stabilize magnetic magnetic islands and sustain continuous burning plasma regimes.", "gemini-1-5", "academic", "gemini_tokamak_fusion"),
    ("The integration of wide-bandgap semiconductor devices, specifically silicon carbide (SiC) and gallium nitride (GaN), is revolutionizing power conversion efficiency in high-voltage electric vehicle drivetrains. Compared to legacy silicon IGBTs, wide-bandgap transistors exhibit higher critical breakdown electric fields, faster switching frequencies, and reduced thermal dissipation losses. Consequently, power inverters can be miniaturized significantly, extending vehicle driving range while simplifying cooling architectures.", "gemini-1-5", "academic", "gemini_sic_semis"),
    ("Green hydrogen synthesis via proton-exchange membrane (PEM) water electrolysis represents a crucial vector for decarbonizing heavy industrial sectors, such as steel manufacturing and ammonia production. Operating at high current densities, PEM electrolyzers respond rapidly to fluctuating power inputs from collocated solar and wind installations. However, reliance on scarce platinum-group metal catalysts, specifically iridium oxide on anode surfaces, poses a scaling bottleneck that necessitates novel earth-abundant catalyst discovery.", "gemini-1-5", "academic", "gemini_green_h2_pem"),
    ("Cryogenic carbon capture technologies offer promising post-combustion abatement pathways for hard-to-abate industrial point sources like cement kilns and blast furnaces. By desublimating carbon dioxide directly from conditioned flue gases at temperatures below minus one hundred Celsius, the process produces high-purity solid dry ice without requiring corrosive chemical amine solvents. Subsequent pressurization converts the solid into dense-phase liquid CO2 suitable for secure geological sequestration.", "gemini-1-5", "academic", "gemini_cryo_carbon"),

    # Llama 3.3 70B
    ("Distributed telemetry frameworks utilizing the OpenTelemetry standard have become an essential requirement for managing complex microservice architectures. Modern cloud-native applications comprise hundreds of loosely coupled services communicating across asynchronous gRPC and REST interfaces. Propagating contextual trace identifiers through distributed headers enables software reliability engineers to pinpoint latency spikes and cascading failures across microservice boundaries. Consequently, unified telemetry observability is fundamental to modern site reliability engineering.", "llama-3-3", "academic", "llama_opentelemetry"),
    ("Horizontal pod autoscaling algorithms in Kubernetes container orchestration clusters continuously adjust replica counts based on observed CPU utilization and custom application metrics. When incoming HTTP request rates spike, predictive autoscaling controllers evaluate trailing resource velocity to spawn container instances before latency degradations trigger customer timeouts. Balancing cluster elasticity with node provisioning overhead represents an ongoing operational trade-off in high-throughput cloud infrastructure.", "llama-3-3", "academic", "llama_k8s_autoscaling"),
    ("Industrial supervisory control and data acquisition (SCADA) networks increasingly face sophisticated cybersecurity threats targeting programmable logic controllers (PLCs). Traditional air-gapped operational technology environments have been breached by weaponized USB vectors and supply-chain firmware compromises. Implementing cryptographically signed firmware verification alongside passive deep packet inspection of industrial fieldbus protocols is imperative to prevent malicious operational setpoint manipulation.", "llama-3-3", "academic", "llama_scada_security"),
    ("Edge computing optimization for industrial robotics utilizes hardware-accelerated tensor processing units to execute quantized computer vision algorithms directly at the robotic gripper assembly. By processing high-speed camera frames locally with sub-ten-millisecond latency, robotic sorting systems achieve precision pick-and-place throughput without incurring cloud round-trip networking delays. Furthermore, local edge inference preserves data privacy on factory production lines.", "llama-3-3", "academic", "llama_edge_robotics"),
    ("Non-Volatile Memory Express over Fabrics (NVMe-oF) storage network architectures leverage Remote Direct Memory Access (RDMA) to bridge low-latency solid-state drive pools with distributed compute clusters. By bypassing host kernel networking stacks, NVMe-oF delivers microsecond access times across Ethernet RoCE and InfiniBand fabrics comparable to direct-attached PCIe storage devices. This high-throughput storage topology accelerates distributed deep learning training pipelines significantly.", "llama-3-3", "academic", "llama_nvme_fabrics")
]

NEW_QWEN_TEXTS = [
    ("The optimization of ultra-deep underground mining ventilation systems requires advanced computational thermodynamics to manage geothermal heat dissipation. At excavation depths exceeding two thousand meters, virgin rock temperatures can reach sixty degrees Celsius. Mechanical refrigeration plants must chill recirculating air masses while scrubbing toxic particulate matter generated by blasting operations.", "qwen-2-5", "qwen_deep_mine"),
    ("Quantum key distribution (QKD) protocols utilize entangled photon pairs to achieve information-theoretically secure cryptographic communications. By exploiting the no-cloning theorem of quantum mechanics, any eavesdropping attempt inevitably introduces detectable quantum bit error rates into the transmission channel, allowing communicating parties to abort compromised key exchanges immediately.", "qwen-2-5", "qwen_qkd_entanglement"),
    ("The metallurgical fabrication of high-entropy alloys combines five or more principal metallic elements in equiatomic proportions. Unlike conventional alloys based on a single solvent element, high-entropy alloys exhibit high configurational entropy that stabilizes simple solid-solution phases. This atomic micro-structure provides exceptional yield strength and fracture toughness at cryogenic temperatures.", "qwen-2-5", "qwen_hea_alloys"),
    ("Modern autonomous container terminal logistics rely on automated guided vehicles (AGVs) coordinated through centralized multi-agent pathfinding algorithms. By solving space-time conflict graphs in real time, the supervisory fleet management system optimizes container transport between quayside gantry cranes and automated stacking yards without traffic deadlocks.", "qwen-2-5", "qwen_terminal_agv"),
    ("Synthetic biology approaches to metabolic pathway engineering enable the biosynthesis of complex natural alkaloids within engineered Saccharomyces cerevisiae yeast strains. By expressing heterologous plant enzymes in targeted subcellular compartments, metabolic engineers optimize carbon flux toward therapeutic artemisinin and precursor molecules while minimizing cytotoxic intermediate accumulation.", "qwen-2-5", "qwen_synbio_yeast")
]

NEW_DEEPSEEK_TEXTS = [
    ("A rigorous topological analysis of continuous gravitational wave detection strategies indicates that all-sky searches for rapidly rotating non-axisymmetric neutron stars remain constrained by prohibitive computational complexity. Because parameter spaces encompass source position, frequency, and spindown derivatives, semi-coherent Hough transform algorithms must balance sensitivity against memory bandwidth in distributed GPU clusters.", "deepseek-v3", "deepseek_grav_waves"),
    ("The asymptotic safety paradigm in non-perturbative quantum gravity posits that gravitational interactions achieve ultraviolet completeness through an interacting fixed point of the renormalization group flow. Utilizing functional renormalization group techniques, researchers establish that gravitational coupling constants flow toward a non-trivial ultraviolet attractor, avoiding non-renormalizable divergence.", "deepseek-v3", "deepseek_asymptotic_safety"),
    ("An analytical evaluation of Bayesian neural networks under variational inference reveals that mean-field Gaussian approximations systematically underestimate posterior parameter variance in multimodal loss landscapes. Employing normalizing flows or Hamiltonian Monte Carlo sampling yields superior epistemic uncertainty calibration, mitigating overconfidence on out-of-distribution input manifolds.", "deepseek-v3", "deepseek_bnn_variational"),
    ("In developmental epigenetics, chromatin remodeling complexes govern transcriptional repression through polycomb group protein recruitment. PRC2 catalyzes trimethylation of histone H3 lysine 27, establishing repressive heterochromatic domains across developmental gene promoters. Misregulation of this epigenetic silencing mechanism frequently triggers oncogenic lineage dedifferentiation.", "deepseek-v3", "deepseek_polycomb_prc2"),
    ("The continuum mechanics of non-Newtonian viscoplastic fluids in subterranean hydraulic fracturing involves complex rheological transitions between solid elastic behavior and shear-thinning fluid flow. Herschel-Bulkley constitutive equations model proppant transport along propagating planar fracture corridors, determining final fracture conductivity in tight hydrocarbon reservoirs.", "deepseek-v3", "deepseek_viscoplastic_rheo")
]


def update_script():
    with open(EXPAND_SCRIPT, "r", encoding="utf-8") as f:
        content = f.read()

    # Find and append to HUMAN_TEXTS
    ht_marker = "HUMAN_TEXTS = ["
    idx_ht = content.find(ht_marker)
    if idx_ht != -1:
        # Find the closing bracket of HUMAN_TEXTS
        close_ht = content.find("\n]\n\nESL_TEXTS", idx_ht)
        if close_ht != -1:
            ht_additions = ",\n" + ",\n".join([f'    ({repr(t[0])}, {repr(t[1])}, {repr(t[2])})' for t in NEW_HUMAN_TEXTS])
            content = content[:close_ht] + ht_additions + content[close_ht:]

    # Find and append to ESL_TEXTS
    esl_marker = "ESL_TEXTS = ["
    idx_esl = content.find(esl_marker)
    if idx_esl != -1:
        close_esl = content.find("\n]\n\nAI_IN_DIST_TEXTS", idx_esl)
        if close_esl != -1:
            esl_additions = ",\n" + ",\n".join([f'    ({repr(t[0])}, {repr(t[1])}, {repr(t[2])})' for t in NEW_ESL_TEXTS])
            content = content[:close_esl] + esl_additions + content[close_esl:]

    # Find and append to AI_IN_DIST_TEXTS
    ai_marker = "AI_IN_DIST_TEXTS = ["
    idx_ai = content.find(ai_marker)
    if idx_ai != -1:
        close_ai = content.find("\n]\n\nQWEN_UNSEEN_TEXTS", idx_ai)
        if close_ai != -1:
            ai_additions = ",\n" + ",\n".join([f'    ({repr(t[0])}, {repr(t[1])}, {repr(t[2])}, {repr(t[3])})' for t in NEW_AI_TEXTS])
            content = content[:close_ai] + ai_additions + content[close_ai:]

    # Find and append to QWEN_UNSEEN_TEXTS
    qwen_marker = "QWEN_UNSEEN_TEXTS = ["
    idx_qwen = content.find(qwen_marker)
    if idx_qwen != -1:
        close_qwen = content.find("\n]\n\nDEEPSEEK_UNSEEN_TEXTS", idx_qwen)
        if close_qwen != -1:
            qwen_additions = ",\n" + ",\n".join([f'    ({repr(t[0])}, {repr(t[1])}, {repr(t[2])})' for t in NEW_QWEN_TEXTS])
            content = content[:close_qwen] + qwen_additions + content[close_qwen:]

    # Find and append to DEEPSEEK_UNSEEN_TEXTS
    ds_marker = "DEEPSEEK_UNSEEN_TEXTS = ["
    idx_ds = content.find(ds_marker)
    if idx_ds != -1:
        close_ds = content.find("\n]\n\n\ndef assemble_and_save():", idx_ds)
        if close_ds != -1:
            ds_additions = ",\n" + ",\n".join([f'    ({repr(t[0])}, {repr(t[1])}, {repr(t[2])})' for t in NEW_DEEPSEEK_TEXTS])
            content = content[:close_ds] + ds_additions + content[close_ds:]

    with open(EXPAND_SCRIPT, "w", encoding="utf-8") as f:
        f.write(content)

    print("[Update] Successfully updated expand_data_richness.py with all new text corpora.")


if __name__ == "__main__":
    update_script()
